Repository micronaut-projects/micronaut-mongodb, pull requests merged in 2020-08, with the labels that each got.

#81 [mongodb] Update common files for branch 1.3.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#80 [mongodb] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#83 [mongodb] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#84 [mongodb] Update common files for branch 1.3.x
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#85 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#87 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#92 [mongodb] Update common files for branch 2.1.x
  .github/workflows/release-notes.yml
Labels: relates-to: build

#91 [mongodb] Update common files for branch master
  .github/workflows/release-notes.yml
Labels: relates-to: build

#35 Upgrade to Micronaut 2.x
  gradle.properties
  mongo-reactive/build.gradle
  mongo-sync/build.gradle
Labels: status: future consideration
