Repository micronaut-projects/micronaut-mongodb, pull requests merged in 2022-05, with the labels that each got.

#304 [mongodb] Update common files for branch master
  .github/dependabot.yml
Labels: relates-to: build

#293 Dependency upgrades
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#309 [mongodb] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#310 Adds links to Micronaut Data and Guides
  src/main/docs/guide/introduction.adoc
Labels: type: docs

#313 [mongodb] Update common files for branch master
  .github/release.yml
  .github/renovate.json
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#314 [mongodb] Update common files for branch master
  .github/release.yml
  .github/workflows/graalvm.yml
Labels: relates-to: build
